server:
  port: 10004


spring:
  datasource:                                         # 数据源的相关配置
    # 拆分数据源到独立的database instance ，或者独立的schema
#    url: jdbc:mysql://localhost:3306/foodie-cloud-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
    # Redis的单机单实例
    host: localhost  #192.168.15.100
    database: 1
    port: 6379
#    password: imooc


    # Redis 哨兵模式
#    database: 1
#    password: imooc
#    sentinel:
#      master: imooc-mastershard-order@192.168.15.106
#      nodes: 192.168.15.100:26379,192.168.15.101:26379,192.168.15.102:26379
    # Redis 集群模式
#    database:集群模式下没有database这种概念
#    password: imooc
#    cluster:
#      nodes: 192.168.15.100:26379,192.168.15.101:26379,192.168.15.102:26379,192.168.15.104:26379,192.168.15.105:26379,192.168.15.106:26379


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出的日志实现StdOutImpl

